In [3]:
# Initialize Otter
import otter
grader = otter.Notebook("hwk1-task2-corals.ipynb")

ModuleNotFoundError: No module named 'otter'

# Task 2: Exploring coral diversity data

## Instructions 

- First, update the following cell to have a link to *your* Homework 1 GitHub repository:

**UPDATE THIS LINK:**

[https://github.com/cllorey/eds220-hwk1.git]()

- This task covers topics on the lesson on [subsetting `pandas.DataFrames`](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.html). The best strategy to solve it is to get together with your classmates and work on it together after that lecture.

- Review the [complete rubric for this task](https://docs.google.com/document/d/131OnUDOLpOl94SlaMU9nGqT998ABrjFS/edit?usp=sharing&ouid=111507336322611936333&rtpof=true&sd=true) before starting.

- **Make at least 5 commits at moments you think are adequate.** We'll check your repository and view the commit history.

- **Add comments for all your code.** Err on the side of commenting too much for now. Comments should follow best practices.

<!-- BEGIN QUESTION -->


## 1
For this task we are going to use data about  [Western Indian Ocean Coral Diversity (McClanahan, 2023)](https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1K35S3H) from the Knowledge Network for Biocomplexity (KNB) data repository. 

a. Navigate to the dataset's link and explore the data package. 
 
b. Use the next markdown cell to add a brief description of the dataset, including a citation, date of access, and a link to the archive.

**Description:** This dataset contains information on coral cover, coral diversity, water quality/conditions, resource management, and climate stress in the Western Indian Ocean from 1998 to 2022.
**Citation:** Tim McClanahan. (2023). *Western Indian Ocean Coral Diversity.* Knowledge Network for Biocomplexity. [doi:10.5063/F1K35S3H](doi:10.5063/F1K35S3H).
**Date of Access:** Monday, October 5th, 2026
**Link to Archive:** [Western Indian Ocean Coral Diversity (McClanahan, 2023)](https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1K35S3H)

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 2
In the next code cell, import the `pandas` package using standard abbreviation in a code cell.

Read in the data from the URL using the `pd.read_csv` function and store it as `coral_div` like this:

```
# read in data
coral_div = pd.read_csv('the URL goes here')
```

In [4]:
import pandas as pd
coral_div = pd.read_csv('data/coral_data.csv')

<!-- END QUESTION -->

## 3

Use attributes and methods of the `coral_div` data frame to obtain the following information about it:

Use the code cells marked a-e. For each, add a comment explaining what is the ouput.

a. how many rows and columns does it have? Store your answers in the `rows` and `columns` variables.

In [15]:
# Check the shape of the data frame
print(coral_div.shape)
rows = 575
columns = 42

(575, 42)

In [5]:
grader.check("q3_a")

NameError: name 'grader' is not defined

b. What are the column names? Store your answer in the `coral_div_columns` variable.

In [20]:
# Print the data frame's column names
coral_div_columns = coral_div.columns
coral_div_columns

Index(['PU_ID', 'PU_Lat', 'PU_Lon', 'Number_of_genera', 'Country', 'Ecoregion',
       'Management', 'Habitat', 'Observer', 'Depth', 'Coralcover',
       'SSTRateofRise', 'PARmax', 'Calcite', 'Dis_oxygen', 'mean.waveNRJ',
       'Salinity_mean', 'andrello_reef_value', 'andrello_nutrients',
       'mean.npp', 'TT_market_hrs', 'TT_pop_hrs', 'cumDHW', 'SST_Kurtosis',
       'SST_Median', 'ChlorA_median', 'andrello_sediments', 'Current_vel_mean',
       'Diff_attenuation', 'Grav_NP', 'Grav_NC', 'PH', 'SST_bimodality',
       'SST_Skewness', 'ClimateStressModel', 'Netflow', 'Indegree',
       'Outdegree', 'Retention', 'min_yr', 'max_yr', 'no_replicates'],
      dtype='object')

In [ ]:
grader.check("q3_b")

c. what are the data types of the columns? Store your answer in the `coral_div_types`.

In [21]:
# List the data types of each column
coral_div_types = coral_div.dtypes
coral_div_types

PU_ID                    int64
PU_Lat                 float64
PU_Lon                 float64
Number_of_genera         int64
Country                 object
Ecoregion               object
Management              object
Habitat                 object
Observer                object
Depth                  float64
Coralcover               int64
SSTRateofRise          float64
PARmax                 float64
Calcite                float64
Dis_oxygen             float64
mean.waveNRJ           float64
Salinity_mean          float64
andrello_reef_value      int64
andrello_nutrients     float64
mean.npp               float64
TT_market_hrs          float64
TT_pop_hrs             float64
cumDHW                 float64
SST_Kurtosis           float64
SST_Median             float64
ChlorA_median          float64
andrello_sediments     float64
Current_vel_mean       float64
Diff_attenuation       float64
Grav_NP                float64
Grav_NC                float64
PH                     float64
SST_bimodality         float64
SST_Skewness           float64
ClimateStressModel     float64
Netflow                float64
Indegree               float64
Outdegree              float64
Retention              float64
min_yr                   int64
max_yr                   int64
no_replicates            int64
dtype: object

In [ ]:
grader.check("q3_c")

d. display the first 8 rows with all the column names. For this one, you will need to udpate a `pandas` option (HINT: check the first discussion section). Store your answer in the `first_8_rows` variable.

In [23]:
# Print the data frame's first 8 rows
first_8_rows = coral_div.head(8)

In [24]:
# View the dataframe 
first_8_rows

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
0,7,39.076711,-5.490011,35,Tanzania,East African Coral Coast,UnfishedLow,Crest,Tim,11.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2019,2019,1
1,7,39.076711,-5.490011,22,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2010,2015,2
2,7,39.076711,-5.490011,25,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,4.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2015,2015,1
3,7,39.076711,-5.490011,26,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2016,2019,2
4,10,39.054253,-5.512514,27,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,1.5,...,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2010,2019,3
5,10,39.054253,-5.512514,29,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,1.5,...,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2015,2015,1
6,15,39.054253,-5.535017,19,Tanzania,East African Coral Coast,Restricted,Crest,Tim,8.0,...,0.461297,-0.134548,0.595600,0.011721,112.75,51.50,183.75,2019,2019,1
7,39,39.009337,-5.647518,28,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.0,...,0.464874,-0.158601,0.626000,-0.063087,96.50,40.75,35.75,2015,2019,3

In [ ]:
grader.check("q3_d")

<!-- BEGIN QUESTION -->

e. Write code to find out some other inital information you are interested in.

In [25]:
# Print the data frame's last 8 rows
last_8_rows = coral_div.tail(8)
last_8_rows

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
567,11680,32.878336,-27.011417,20,South Africa,Delagoa,Restricted,Slope,Carlos,13.000000,...,0.568628,0.08475,0.37175,0.030092,15.75,17.0,86.5,2005,2007,4
568,11680,32.878336,-27.011417,22,South Africa,Delagoa,Restricted,Slope,Porter,10.800000,...,0.568628,0.08475,0.37175,0.030092,15.75,17.0,86.5,2022,2022,1
569,11680,32.878336,-27.011417,20,South Africa,Delagoa,Restricted,Slope,Sink,13.833333,...,0.568628,0.08475,0.37175,0.030092,15.75,17.0,86.5,2015,2017,6
570,11681,32.878336,-27.011417,19,South Africa,Delagoa,Restricted,Slope,Sink,15.500000,...,0.568628,0.08475,0.37175,0.030092,15.75,17.0,86.5,2015,2016,2
571,11682,32.878336,-27.011417,18,South Africa,Delagoa,Restricted,Slope,Carlos,12.000000,...,0.568628,0.08475,0.37175,0.030092,15.75,17.0,86.5,2007,2007,2
572,11683,32.878336,-27.011417,19,South Africa,Delagoa,Restricted,Slope,Carlos,12.600000,...,0.568628,0.08475,0.37175,0.030092,15.75,17.0,86.5,2005,2007,10
573,11683,32.878336,-27.011417,19,South Africa,Delagoa,Restricted,Slope,Porter,13.000000,...,0.568628,0.08475,0.37175,0.030092,15.75,17.0,86.5,2022,2022,4
574,11683,32.878336,-27.011417,21,South Africa,Delagoa,Restricted,Slope,Sink,13.470000,...,0.568628,0.08475,0.37175,0.030092,15.75,17.0,86.5,2015,2017,15

In [26]:
# Look at summary statistics for the data frame's numerical observations
coral_div.describe()

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
count,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,...,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000
mean,3536.620870,43.976240,-12.633028,20.182609,6.253192,38.340870,0.017559,55.558422,0.003622,4.684780,...,0.529946,-0.071522,0.549405,0.203586,51.882609,55.963043,91.107391,2013.165217,2013.923478,1.716522
std,2345.438008,6.549987,6.972048,6.568299,4.501193,10.586395,0.006552,2.118008,0.007026,0.108744,...,0.047659,0.127463,0.151452,0.344229,37.238322,27.701567,147.657638,4.693628,4.638243,1.524934
min,7.000000,32.878336,-27.011417,3.000000,0.500000,10.000000,-0.000463,48.774500,0.000058,4.373000,...,0.416042,-0.297088,0.081800,-0.576851,2.500000,10.500000,0.000000,1998.000000,1998.000000,1.000000
25%,1413.500000,39.413579,-20.006995,16.000000,2.000000,31.000000,0.015466,54.117250,0.000272,4.626000,...,0.488628,-0.168714,0.470100,-0.023227,21.250000,35.625000,11.750000,2009.000000,2010.000000,1.000000
50%,4002.000000,40.671221,-12.827030,20.000000,5.000000,39.000000,0.019233,55.523998,0.000906,4.711000,...,0.547940,-0.095642,0.579325,0.233054,43.500000,54.250000,47.750000,2014.000000,2015.000000,1.000000
75%,5182.000000,48.497793,-5.523765,24.000000,9.500000,45.000000,0.021978,57.133999,0.002866,4.755500,...,0.570981,0.018935,0.656300,0.509071,81.250000,77.000000,109.000000,2016.000000,2018.000000,2.000000
max,11683.000000,57.806585,-1.745137,40.000000,29.000000,60.000000,0.027391,62.193001,0.055976,4.850250,...,0.598189,0.304314,0.813600,0.815635,146.750000,136.000000,1561.500000,2022.000000,2022.000000,19.000000

In [35]:
# Check for NAs in columns by using `isnull().sum()`
coral_div.isnull().sum() 

# Or by using `.info()`
coral_div.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575 entries, 0 to 574
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PU_ID                575 non-null    int64
 1   PU_Lat               575 non-null    float64
 2   PU_Lon               575 non-null    float64
 3   Number_of_genera     575 non-null    int64
 4   Country              575 non-null    object
 5   Ecoregion            575 non-null    object
 6   Management           575 non-null    object
 7   Habitat              530 non-null    object
 8   Observer             575 non-null    object
 9   Depth                575 non-null    float64
 10  Coralcover           575 non-null    int64
 11  SSTRateofRise        575 non-null    float64
 12  PARmax               575 non-null    float64
 13  Calcite              575 non-null    float64
 14  Dis_oxygen           575 non-null    float64
 15  mean.waveNRJ         575 non-null    float64
 16  Salinity_mean        575 non-null    float64
 17  andrello_reef_value  575 non-null    int64
 18  andrello_nutrients   575 non-null    float64
 19  mean.npp             575 non-null    float64
 20  TT_market_hrs        575 non-null    float64
 21  TT_pop_hrs           575 non-null    float64
 22  cumDHW               575 non-null    float64
 23  SST_Kurtosis         575 non-null    float64
 24  SST_Median           575 non-null    float64
 25  ChlorA_median        575 non-null    float64
 26  andrello_sediments   575 non-null    float64
 27  Current_vel_mean     567 non-null    float64
 28  Diff_attenuation     575 non-null    float64
 29  Grav_NP              575 non-null    float64
 30  Grav_NC              575 non-null    float64
 31  PH                   575 non-null    float64
 32  SST_bimodality       575 non-null    float64
 33  SST_Skewness         575 non-null    float64
 34  ClimateStressModel   575 non-null    float64
 35  Netflow              575 non-null    float64
 36  Indegree             575 non-null    float64
 37  Outdegree            575 non-null    float64
 38  Retention            575 non-null    float64
 39  min_yr               575 non-null    int64
 40  max_yr               575 non-null    int64
 41  no_replicates        575 non-null    int64
dtypes: float64(30), int64(7), object(5)
memory usage: 188.8+ KB

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 4

Some of the columns have data type `int64` and some have data type `float64`. What is the difference between these `int64` and `float64`?

`int64` means that the data type is an integer, whereas `float64` contains decimals.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 5

The `Country` column indicates the country where the coral reef is located. Explain, in your own words, what is the ouput of `coral_div['Country']` and `coral_div['Country'].unique()`.

`coral_div['Country']` returns a pandas Series that displays all of the values in the 'Country' column.

`coral_div['Country'].unique()` returns a list of unique values in the 'Country' column (in simpler terms, it lists all the countries in the 'Country' column).

<!-- END QUESTION -->

## 6

Check the dataset's [metadata file README_md.doc](https://knb.ecoinformatics.org/view/doi:10.5063/F1K35S3H) to find which column has information about who made an observation. How many observers collected this data? HINT: Check this [method for `pandas.DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nunique.html). Store your answer in the `unique_observers` variable.

In [47]:
# Find the unique values in the 'Observer' column
unique_observers = coral_div['Observer'].nunique()
unique_observers

16

In [ ]:
grader.check("q6")

## 7

The `Coralcover` column indicates the percent of hard coral cover in each 6 km reef cell surveyed.

<!-- BEGIN QUESTION -->

a)  Describe, in detail,  what kind of object `coral_div['Coralcover']>= 50` is.

This code returns a pandas Series that stores boolean (True/False) values.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

b) What data is `coral_div[coral_div['Coralcover'] >= 50]` selecting?

This code is selecting a subset of the coral_div data frame that includes all observations where the coral cover is greater than 50 percent.

<!-- END QUESTION -->

## 8

Use code to find if there are there any sites with a 30% coral cover in Tanzania. Store your answer in the `coral_cover` variable.

In [51]:
# Filter for observations where coral cover is 30%
coral_cover = coral_div[coral_div['Coralcover'] == 30]

In [53]:
# View the dataframe
pd.set_option('display.max_columns', None)
coral_cover

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,mean.waveNRJ,Salinity_mean,andrello_reef_value,andrello_nutrients,mean.npp,TT_market_hrs,TT_pop_hrs,cumDHW,SST_Kurtosis,SST_Median,ChlorA_median,andrello_sediments,Current_vel_mean,Diff_attenuation,Grav_NP,Grav_NC,PH,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
63,693,39.391121,-5.782490,10,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,5.000000,30,0.015676,52.992001,0.037043,4.7580,5.885771,35.099083,1156,1.507334,958.495666,0.950000,0.550000,30.656667,-0.940944,27.362500,0.225574,26.068680,0.716784,0.0730,0.004944,0.779117,8.215,0.490512,-0.101724,0.655600,-0.309514,77.00,65.25,147.50,2018,2018,2
64,697,39.391121,-5.804983,22,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.166667,30,0.015599,52.992001,0.037043,4.7580,5.285148,35.099083,1156,1.507334,968.100098,0.950000,0.550000,30.021056,-0.942581,27.360000,0.217308,26.068680,0.716784,0.0730,0.004944,0.779117,8.215,0.490769,-0.100365,0.683050,-0.309514,77.00,65.25,147.50,2010,2018,3
122,867,39.368664,-4.656797,23,Kenya,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.666667,30,0.019138,54.446501,0.001744,4.7110,3.910353,35.137687,393,2.272863,973.582092,1.783333,0.333333,24.709971,-0.770055,27.210000,0.733985,3969.175781,0.763393,0.1165,0.021011,70.412808,8.215,0.448886,-0.036279,0.727025,0.629931,43.50,47.00,53.25,2014,2021,3
123,867,39.368664,-4.656797,26,Kenya,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,1.000000,30,0.019138,54.446501,0.001744,4.7110,3.910353,35.137687,393,2.272863,973.582092,1.783333,0.333333,24.709971,-0.770055,27.210000,0.733985,3969.175781,0.763393,0.1165,0.021011,70.412808,8.215,0.448886,-0.036279,0.727025,0.629931,43.50,47.00,53.25,2012,2012,1
124,868,39.391121,-4.656797,24,Kenya,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,4.000000,30,0.018781,54.446501,0.001744,4.7110,3.910353,35.137687,61,2.485976,973.582092,1.750000,0.283333,24.628334,-0.776498,27.210000,0.636012,1783.397461,0.763393,0.1165,0.063383,72.654408,8.215,0.450158,-0.035417,0.723350,0.629931,43.50,47.00,53.25,2011,2011,2
125,868,39.391121,-4.656797,20,Kenya,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.187500,30,0.018781,54.446501,0.001744,4.7110,3.910353,35.137687,61,2.485976,973.582092,1.750000,0.283333,24.628334,-0.776498,27.210000,0.636012,1783.397461,0.763393,0.1165,0.063383,72.654408,8.215,0.450158,-0.035417,0.723350,0.629931,43.50,47.00,53.25,2014,2021,8
126,868,39.391121,-4.656797,22,Kenya,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,4.000000,30,0.018781,54.446501,0.001744,4.7110,3.910353,35.137687,61,2.485976,973.582092,1.750000,0.283333,24.628334,-0.776498,27.210000,0.636012,1783.397461,0.763393,0.1165,0.063383,72.654408,8.215,0.450158,-0.035417,0.723350,0.629931,43.50,47.00,53.25,2016,2019,3
127,872,39.436037,-4.679331,22,Kenya,East African Coral Coast,Restricted,Slope,Tim,29.000000,30,0.018396,54.683998,0.000140,4.7130,4.377082,34.970097,62,1.823716,946.795227,1.750000,0.283333,24.045726,-0.784624,26.776667,0.316760,1916.254883,0.234075,0.0700,0.063383,72.654408,8.214,0.451827,-0.035988,0.628700,0.629931,43.50,47.00,53.25,2009,2009,1
139,1186,55.246386,-21.012018,19,Reunion,Mascarene Islands,Restricted,NaN,Mireille,2.500000,30,0.024752,55.993999,0.000101,4.7390,37.335079,35.131153,14635,0.000000,555.469055,0.550000,0.066667,68.881183,-1.242937,25.700000,0.103709,0.000000,0.028523,0.0360,1.710044,128.876252,8.271,0.568952,-0.009900,0.212200,-0.055715,11.75,14.00,36.00,2005,2005,1
210,2377,49.968784,-15.717807,15,Madagascar,Western and Northern Madagascar,Fished,NaN,Tim,8.500000,30,0.019783,52.161999,0.000384,4.6080,2.077716,34.964661,0,0.004356,2638.477295,8.450000,0.033333,51.258121,-1.283946,26.680000,1.680361,57.260605,0.096964,0.1720,1.724709,0.802782,8.233,0.596164,-0.153239,0.470300,0.349270,18.50,89.00,33.75,2005,2005,1
341,4294,39.211458,-4.814515,37,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,30,0.018789,53.858002,0.002154,4.7170,3.129188,35.120766,0,1.233231,996.539490,1.216667,0.266667,23.736330,-0.779552,27.245000,0.470832,1746.570435,0.653534,0.1210,0.004043,42.349168,8.216,0.451293,-0.048992,0.608900,0.514920,46.00,49.50,82.75,2018,2018,1
342,4299,39.233916,-4.837043,26,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,12.500000,30,0.018789,53.937000,0.001265,4.7195,2.233872,35.125887,0,1.233231,1018.213928,1.550000,0.566667,23.736330,-0.779552,27.250000,0.462739,1746.570435,0.653883,0.1115,0.000879,25.914153,8.216,0.451293,-0.048992,0.601725,0.514920,46.00,49.50,82.75,2018,2018,2
343,4302,39.211458,-4.859570,31,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,7.000000,30,0.018462,54.015999,0.000377,4.7220,0.179306,35.131008,0,1.233231,1071.519775,1.550000,0.566667,23.285391,-0.784669,27.260000,0.469467,1746.570435,0.654233,0.1020,0.000879,25.914153,8.216,0.452402,-0.050477,0.595200,0.514920,46.00,49.50,82.75,2018,2018,1
344,4303,39.301290,-4.859570,23,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,30,0.018270,53.937000,0.002104,4.7220,2.600268,35.174747,0,0.611645,965.657349,1.733333,0.800000,24.659219,-0.792062,27.255000,0.339959,858.381897,0.738552,0.0960,0.000426,20.656527,8.216,0.453806,-0.048007,0.602300,0.514920,46.00,49.50,82.75,2018,2018,1
377,4906,39.660616,-4.972195,33,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.000000,30,0.016549,53.943001,0.000076,4.7270,0.034857,34.968960,345,0.063687,980.656921,1.550000,0.700000,27.144278,-0.941926,27.215000,0.212634,23.135084,0.234671,0.0620,0.038530,3.044183,8.213,0.488396,-0.074229,0.671900,0.156359,66.75,41.75,38.00,2013,2013,2
388,5049,39.615700,-5.490011,14,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,4.000000,30,0.015241,52.493000,0.000155,4.7485,8.124817,34.976822,0,0.104816,755.473267,2.066667,0.583333,26.566285,-0.935094,25.715000,0.158397,9.305736,0.406605,0.0625,0.003125,1.727036,8.213,0.489921,-0.109523,0.657000,-0.328399,93.25,57.25,650.25,2018,2018,1
389,5050,39.638158,-5.490011,18,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,6.000000,30,0.015241,52.493000,0.000155,4.7485,8.124817,34.976822,0,0.104816,755.473267,2.066667,0.583333,26.566285,-0.935094,25.710000,0.224526,9.305736,0.406605,0.0625,0.003125,1.727036,8.213,0.489921,-0.109523,0.618825,-0.328399,93.25,57.25,650.25,2018,2018,1

In [ ]:
grader.check("q8")

## 9

We are interested in looking at the PH of sea water (`PH` column),  mean salinity (`Salinity_mean` column), and depth of survey location in meters (`Depth` column). Subset the data frame by selecting only these column. Store your answer in the `filtered_data` variable

In [57]:
# Filter the data for columns of interest
filtered_data = coral_div[['PH', 'Salinity_mean', 'Depth']]

In [58]:
# View the dataframe
filtered_data.head()

       PH  Salinity_mean  Depth
0  8.2175      35.167646   11.0
1  8.2175      35.167646    2.0
2  8.2175      35.167646    4.0
3  8.2175      35.167646    3.0
4  8.2180      35.102688    1.5

In [ ]:
grader.check("q9")

## 10
The `max_yr` column indicates the year of last sampling at a given site. Select the PH, salinity, and depth for sites where sampling ended in 2017. Store your answer in the `sampling_2017` variable. `Sampling_2017` should include the following columns in the following order: ` PH, Salinity_mean, Depth, max_yr`.

In [ ]:
sampling_2017 = ...

In [ ]:
# View the dataframe 
sampling_2017

In [ ]:
grader.check("q10")

## 11
Use `iloc` to select rows 95 through 100 (including 100) in the 17th, 20th, and 28th columns and assign these values to a new variable called `subset`. View the new `subset` dataframe.

HINT: the ouput columns should be `Salinity_mean`, `mean.npp` and `Current_vel_mean` (in that order!).

In [ ]:
subset = ...

In [ ]:
# View the dataframe
subset

In [ ]:
grader.check("q11")

<!-- BEGIN QUESTION -->

## 12 

Run `subset.isna()`. Explain what this code does and what the output represents.

_Type your answer here, replacing this text._

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 13
Run `subset.isna().any()`. Explain in your own words what this code does and what the output represents. HINT: check the [documentation of `pandas.Sries.any`](https://pandas.pydata.org/docs/reference/api/pandas.Series.any.html).

_Type your answer here, replacing this text._

<!-- END QUESTION -->

## 14 

Select the rows in `subset` that have NA in the `Current_vel_mean` column. Store your answer in the `subset_na` variable.

In [ ]:
subset_na = ...

In [ ]:
# View the dataframe 
subset_na

In [ ]:
grader.check("q14")

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [ ]:
grader.check_all()